<Project Sdk="Dalamud.NET.Sdk/15.0.0">
 <PropertyGroup>
  <DebugType>Full</DebugType>
  <AssemblyVersion>2.0.2.9</AssemblyVersion>
 </PropertyGroup>

 <ItemGroup>
  <Content Include="images\icon.png" CopyToOutputDirectory="Always" />
  <Content Include="TeleporterPlugin.json" CopyToOutputDirectory="Always" />
 </ItemGroup>

 <ItemGroup>
   <PackageReference Update="DalamudPackager" Version="15.0.0" />
   <PackageReference Update="DotNet.ReproducibleBuilds" Version="2.0.2" />
 </ItemGroup>
</Project>
